<?php

return array(
    'key' => 'group_5c9519163d799',
    'title' => 'Modules',
    'fields' => array(
        array(
            'key' => 'field_5c951924e250c',
            'label' => 'Modules',
            'name' => 'modules',
            'type' => 'flexible_content',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layouts' => array(
                '5c9561c747434' => array(
                    'key' => '5c9561c747434',
                    'name' => 'content_section',
                    'label' => 'Content Section',
                    'display' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_5c9563c44bc13',
                            'label' => 'Align',
                            'name' => 'align',
                            'type' => 'radio',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'choices' => array(
                                'left' => 'Left',
                                'right' => 'Right',
                            ),
                            'allow_null' => 0,
                            'other_choice' => 0,
                            'default_value' => 'left',
                            'layout' => 'horizontal',
                            'return_format' => 'value',
                            'save_other_choice' => 0,
                        ),
                        array(
                            'key' => 'field_5c9561e91af35',
                            'label' => 'Image',
                            'name' => 'image',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'url',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                        ),
                        array(
                            'key' => 'field_5c95621c1af36',
                            'label' => 'Heading',
                            'name' => 'heading',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_5c9562761af37',
                            'label' => 'Content',
                            'name' => 'content',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => 5,
                            'new_lines' => 'br',
                        ),
                        array(
                            'key' => 'field_5c9562871af38',
                            'label' => 'CTA',
                            'name' => 'cta',
                            'type' => 'link',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                '5ca3cf9d6b5db' => array(
                    'key' => '5ca3cf9d6b5db',
                    'name' => 'images',
                    'label' => 'Images',
                    'display' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_5ca3cfcf5efc7',
                            'label' => 'Image 1',
                            'name' => 'image_1',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'url',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                        ),
                        array(
                            'key' => 'field_5ca3cfe15efc8',
                            'label' => 'Image 2 Start',
                            'name' => 'image_2_start',
                            'type' => 'range',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'min' => 4,
                            'max' => 12,
                            'step' => 2,
                            'prepend' => '',
                            'append' => '',
                        ),
                        array(
                            'key' => 'field_5ca3d0095efc9',
                            'label' => 'Image 2',
                            'name' => 'image_2',
                            'type' => 'image',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'url',
                            'preview_size' => 'thumbnail',
                            'library' => 'all',
                            'min_width' => '',
                            'min_height' => '',
                            'min_size' => '',
                            'max_width' => '',
                            'max_height' => '',
                            'max_size' => '',
                            'mime_types' => '',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),

                // Begin images repeater block
                '68b0de1f09abf' => array(
                    'key' => '68b0de1f09abf',
                    'name' => 'images_row',
                    'label' => 'Images row',
                    'display' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_68b0de27777b4',
                            'label' => 'Images row',
                            'name' => 'images_row',
                            'type' => 'repeater',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'collapsed' => '',
                            'min' => 4,
                            'max' => 4,
                            'layout' => 'block',
                            'button_label' => '',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_68b0de3d777b5',
                                    'label' => 'Image',
                                    'name' => 'image',
                                    'type' => 'image',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'return_format' => 'url',
                                    'preview_size' => 'thumbnail',
                                    'library' => 'all',
                                    'min_width' => '',
                                    'min_height' => '',
                                    'min_size' => '',
                                    'max_width' => '',
                                    'max_height' => '',
                                    'max_size' => '',
                                    'mime_types' => '',
                                ),
                            ),
                        ),
                    ),
                    'location' => array(
                        array(
                            array(
                                'param' => 'post_type',
                                'operator' => '==',
                                'value' => 'post',
                            ),
                        ),
                    ),
                    'menu_order' => 0,
                    'position' => 'normal',
                    'style' => 'default',
                    'label_placement' => 'top',
                    'instruction_placement' => 'label',
                    'hide_on_screen' => '',
                    'active' => 1,
                    'description' => '',
                ),
                // End images repeater block

                'layout_5c956991bcc4b' => array(
                    'key' => 'layout_5c956991bcc4b',
                    'name' => 'cta_section',
                    'label' => 'CTA Section',
                    'display' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_5c956991bcc4c',
                            'label' => 'Heading',
                            'name' => 'heading',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_5c956991bcc4d',
                            'label' => 'Content',
                            'name' => 'content',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => 5,
                            'new_lines' => 'br',
                        ),
                        array(
                            'key' => 'field_5c956991bcc4e',
                            'label' => 'CTA',
                            'name' => 'cta',
                            'type' => 'link',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'return_format' => 'array',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                '5c95192ad0ff0' => array(
                    'key' => '5c95192ad0ff0',
                    'name' => 'post_slideshow',
                    'label' => 'Post Slideshow',
                    'display' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_5c951939e250d',
                            'label' => 'Slideshow',
                            'name' => 'slideshow_id',
                            'type' => 'post_object',
                            'instructions' => '',
                            'required' => 1,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'post_type' => array(
                                0 => 'torque_post_ss',
                            ),
                            'taxonomy' => array(),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'return_format' => 'id',
                            'ui' => 1,
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                '5c9ba1ad52cd2' => array(
                    'key' => '5c9ba1ad52cd2',
                    'name' => 'region_quick_search',
                    'label' => 'Region Quick Search',
                    'display' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_5cc1d309ed5e3',
                            'label' => 'Regions',
                            'name' => 'regions',
                            'type' => 'taxonomy',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'taxonomy' => 'interra_listing_region',
                            'field_type' => 'checkbox',
                            'add_term' => 0,
                            'save_terms' => 0,
                            'load_terms' => 0,
                            'return_format' => 'id',
                            'multiple' => 0,
                            'allow_null' => 0,
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                '5c9d3f4702dde' => array(
                    'key' => '5c9d3f4702dde',
                    'name' => 'staff_members',
                    'label' => 'Staff Members',
                    'display' => 'block',
                    'sub_fields' => array(),
                    'min' => '',
                    'max' => '',
                ),
                '5c9d3f4702arg' => array(
                    'key' => '5c9d3f4702arg',
                    'name' => 'mailchimp_form',
                    'label' => 'MailChimp Form',
                    'display' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_5c951939e2222',
                            'label' => 'Title',
                            'name' => 'mailchimp_title',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'post_type' => array(),
                            'taxonomy' => array(),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'return_format' => '',
                            'ui' => 1,
                        ),
                        array(
                            'key' => 'field_5c951939e2332',
                            'label' => 'description',
                            'name' => 'mailchimp_desc',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'post_type' => array(),
                            'taxonomy' => array(),
                            'allow_null' => 0,
                            'multiple' => 0,
                            'return_format' => '',
                            'ui' => 1,
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),
                // Headline and content block definition
                '5c9d3f4702arh' => array(
                    'key' => 'group_68af906c5d2fc',
                    'name' => 'headline_and_content',
                    'label' => 'Headline and content',
                    'display' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_68af907cc053c',
                            'label' => 'Headline',
                            'name' => 'headline',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'maxlength' => '',
                        ),
                        array(
                            'key' => 'field_68af90d5c053d',
                            'label' => 'Content',
                            'name' => 'content',
                            'type' => 'textarea',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'placeholder' => '',
                            'maxlength' => '',
                            'rows' => '',
                            'new_lines' => 'br',
                        ),
                    ),
                    'min' => '',
                    'max' => '',
                ),

            ),
            'button_label' => 'Add Module',
            'min' => '',
            'max' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'page',
            ),
            array(
                'param' => 'post_template',
                'operator' => '==',
                'value' => 'default',
            ),
        ),
    ),
    'menu_order' => 10,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
);
