<?php

return array(
    'key' => 'layout_5c956991bcc4b',
    'name' => 'cta_section',
    'label' => 'CTA Section',
    'display' => 'block',
    'sub_fields' => array(
        array(
            'key' => 'field_5c956991bcc4c',
            'label' => 'Heading',
            'name' => 'heading',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5c956991bcc4d',
            'label' => 'Content',
            'name' => 'content',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 5,
            'new_lines' => 'br',
        ),
        array(
            'key' => 'field_5c956991bcc4e',
            'label' => 'CTA',
            'name' => 'cta',
            'type' => 'link',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
        ),
    ),
    'min' => '',
    'max' => '',
);
