<?php

return array(
    'key' => '5ca3cf9d6b5db',
    'name' => 'images',
    'label' => 'Images',
    'display' => 'block',
    'sub_fields' => array(
        array(
            'key' => 'field_5ca3cfcf5efc7',
            'label' => 'Image 1',
            'name' => 'image_1',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array(
            'key' => 'field_5ca3cfe15efc8',
            'label' => 'Image 2 Start',
            'name' => 'image_2_start',
            'type' => 'range',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'min' => 4,
            'max' => 12,
            'step' => 2,
            'prepend' => '',
            'append' => '',
        ),
        array(
            'key' => 'field_5ca3d0095efc9',
            'label' => 'Image 2',
            'name' => 'image_2',
            'type' => 'image',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'url',
            'preview_size' => 'thumbnail',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
    ),
    'min' => '',
    'max' => '',
);
