<?php

return array(
    'key' => '5c9561c747434b',
    'name' => 'torque_filtered_loop',
    'label' => 'Torque Filtered Loop',
    'display' => 'block',
    'sub_fields' => array(
        array(
            'key' => 'field_5c9561c747434c',
            'label' => 'Post Type',
            'name' => 'post_type',
            'type' => 'text',
            'instructions' => 'The post type to query',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 'torque_listing',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5c9561c747434d',
            'label' => 'Posts Per Page',
            'name' => 'posts_per_page',
            'type' => 'number',
            'instructions' => 'Number of posts to display per page',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => 12,
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
        ),
        array(
            'key' => 'field_5c9561c747434e',
            'label' => 'Filters Types',
            'name' => 'filters_types',
            'type' => 'text',
            'instructions' => 'Comma-separated list of filter types (e.g., tabs_acf,dropdown_tax,dropdown_tax)',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_5c9561c747434f',
            'label' => 'Use Template Variation',
            'name' => 'use_template_variation',
            'type' => 'radio',
            'instructions' => 'Enable template variation',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'true' => 'Yes',
                'false' => 'No',
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'default_value' => 'true',
            'layout' => 'horizontal',
            'return_format' => 'value',
            'save_other_choice' => 0,
        ),
        array(
            'key' => 'field_5c9561c7474350',
            'label' => 'Use Custom Label',
            'name' => 'use_custom_label',
            'type' => 'radio',
            'instructions' => 'Enable custom labels',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'true' => 'Yes',
                'false' => 'No',
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'default_value' => 'true',
            'layout' => 'horizontal',
            'return_format' => 'value',
            'save_other_choice' => 0,
        ),
        array(
            'key' => 'field_5c9561c7474351',
            'label' => 'Filters Args',
            'name' => 'filters_args',
            'type' => 'text',
            'instructions' => 'Comma-separated list of filter arguments (e.g., field_5c8ae924ce1a3,interra_listing_property_type,interra_listing_region)',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
    ),
);
